#!/bin/bash

# Do a FFT transform of a picture, then transform it back
# using only the magnitude information

if [ "$#" -lt 1 ]; then
    echo 'magnitudeFFT PICFILE'
    exit 65
fi

PICFILE=$1
PIC=${PICFILE%.*}

echo "Going to convert "$PICFILE

convert $PICFILE -fft $PIC"_fft.png"
convert $PIC"_fft-0.png"  xc:'gray(50%)' -ift $PIC"_magnitude.jpg"
convert $PICFILE $PIC"_magnitude.jpg" +append $PIC"_both.jpg"

rm $PIC"_fft-"*".png"

echo "Magnitude transform: "$PIC"_magnitude.jpg"
echo "Side by side comparison: "$PIC"_both.jpg"
